### ISSUE TITLE
What is the link with open science in week 8? 

### ISSUE THREAD

**Issue by hendelhendel** [SanliFaez/OS4Physicists#12]
The scientific job information market in the tutorial of week 8 as it is proposed, do not have a direct link to open science at all points. There are different options to create that link if needed.

i) Only select the job categories, where a link with Open science can be made
ii) Every professional can be asked, to make a case for open science in their job field.
Iii) Students need to think about the question if and how they want to incorporate, open science in their future job. (This would be my favorite. If the course is taught well, some students are probably willing to incorporate open science in their future job. In this way a seed has been planted!)

**Comment by SanliFaez** [comment]
will consider this when polishing the assignment for week 8.
