### ISSUE TITLE
OS4Physicists Podcast

### ISSUE THREAD

**Issue by hendelhendel** [SanliFaez/OS4Physicists#31]
Share notes on a podcast

**Comment by erikvansebille** [comment]
Not sure I see where a podcast would come in useful in this course. @SanliFaez, you are more a podcast guru than I am; could you check if you see added value of a podcast somewhere in the course?

**Comment by SanliFaez** [comment]
There are plenty of good podcasts on open science. I think they can be used as part of the assignments or perhaps creating a collective source of reviewing and recommending in the class.

here are some *good* podcasts on open science from the scientists perspectives
- [6 episodes of R2OS](https://soundcloud.com/utrechtyoungacademy/sets/the-road-to-open-science-from)
- [Down to earth](https://open.spotify.com/show/4UzkaJKsuePfWABGWSeYNQ?si=93bcf2f470fb4643), from IEEE Geosciences has many nice episodes on all things open science https://open.spotify.com/show/4UzkaJKsuePfWABGWSeYNQ?si=93bcf2f470fb4643
- [ORION open science](https://open.spotify.com/show/4YOeD7DKkoDS5ZSNYZFYtj) narrates mainly from the life sciences perspective 
- [Open Science Talk](https://open.spotify.com/show/4AR79xdrvdvzMI4kjRRU2C?si=355a8224b5c848d7) is a show recorded in Norway with a lot of good interviews
