### ISSUE TITLE
Organize a hackathon

### ISSUE THREAD

**Issue by hendelhendel** [SanliFaez/OS4Physicists#33]
inspiratie voor een opdracht: https://www.hackathon.physics.mcgill.ca/ 
https://garage48.org/blog/hardware-hackathon-inspirations-25-ideas-from-5-years

**Comment by erikvansebille** [comment]
I think a hackathon is a bit too much to ask from the students this first year, and also too much effort to organise. We could always implement a hackathon in a following year; for this first year I suggest to leave it out
