### ISSUE TITLE
Assignment ideas: writing

### ISSUE THREAD

**Issue by hendelhendel** [SanliFaez/OS4Physicists#35]
Essay (personal or group)
Report (personal or groups)
Review (personal or group)
Write a proposal for an open science PhD (personal)

**Comment by SanliFaez** [comment]
I think Essay and Report are not really cool these days. Reviews are useful if they are structured. Can be good for the reproducibility week. 
The proposal for incorporating open science in future research can be a useful exercise, but students need to get true feedback
