### ISSUE TITLE
Assignements idea: On stage

### ISSUE THREAD

**Issue by hendelhendel** [SanliFaez/OS4Physicists#38]
Present an OS topic (groups)
Scientific Pitch (Personal)
Organizing a panel or plenary discussion (group)
Scientific communication outside UU (groups)

**Comment by SanliFaez** [comment]
Organizing a panel discussion or debate is a useful skill, but how to incorporate it for a class of 100?

communicating with outside the class can be a good exercise for the public engagement week. What do you have in mind for that session's exercise @erikvansebille ?

**Comment by erikvansebille** [comment]
> communicating with outside the class can be a good exercise for the public engagement week. What do you have in mind for that session's exercise @erikvansebille ?

Not sure yet, will discuss it with the guest lecturer
