### ISSUE TITLE
Lecture ideas

### ISSUE THREAD

**Issue by hendelhendel** [SanliFaez/OS4Physicists#44]
Forms of story telling
Digital story telling:
https://forestsnews.cifor.org/64958/indonesias-secret-forests-underground-water-world?fnl=en 
https://feature.undp.org/wilderness-of-water/#group-pollution-TttSgKYmyf 
https://www.imperial.ac.uk/stories/mission-to-the-sun/ 
Data story telling: 
https://shorthand.com/the-craft/data-storytelling/index.html

**Comment by SanliFaez** [comment]
this is a very useful TEDx talk covering the science of storytelling and why is it more effective than presenting data and facts. https://www.youtube.com/watch?v=Ez5yS4Q5ASA 

I think these links are useful for your science communication session @erikvansebille
