### ISSUE TITLE
Add info on course logistics to README

### ISSUE THREAD

**Issue by erikvansebille** [SanliFaez/OS4Physicists#5]
Add a section to the README document with course logistics. For example

- [x] scheduling (every Monday morning in block 1?)
- [x] Assignment of groups
- [ ] Option for THPH students to follow only subset of the topics
- [x] ...

**Comment by erikvansebille** [comment]
I'm not sure I entirely understand what the agreements are with Open Science for Theoretical Physics (OSTP). Could you perhaps add that information, @SanliFaez?

**Comment by SanliFaez** [comment]
ITP students can choose to skip lectures 4,5,6,7 but must join 1,2,3,8. They have to make this choice on week 1 and that cannot be exchanged. I will add this at the end of the update process, giving the other course some chance to finalise their syllabus.
