### ISSUE TITLE
Decide about compulsory attendance?

### ISSUE THREAD

**Issue by erikvansebille** [SanliFaez/OS4Physicists#59]
While following-up from #49, I realised that we haven't explicitly decided whether attendance in the Learning Plaza is compulsory. 

If so, how are we going to check? How many lectures can students maximally skip before they fail?

**Comment by SanliFaez** [comment]
my suggestion is to not make it compulsory, but connect the grading of each activity to active participation, as judged by the other team members. This might encourage each student to find alternatives for contributing if they can really not make it to the class.

**Comment by SanliFaez** [comment]
please close this issue if you agree.
I think this is also a topic that students can decide on when writing the code of conduct on week 1.
