### ISSUE TITLE
Week5 info is now about storytelling; but should be about open design/open hardware

### ISSUE THREAD

**Issue by erikvansebille** [SanliFaez/OS4Physicists#63]
See https://github.com/SanliFaez/OS4Physicists/blob/main/CourseDevelopment/Week5/Chapter5.MD. Not sure where the open design/open hardware markdown file is. Can you fix this, @SanliFaez?

**Comment by SanliFaez** [comment]
#64 fixed the issue. storytelling and public engagement is now chapter 6 as agreed.
