### ISSUE TITLE
Wet open overheid

### ISSUE THREAD

**Issue by veldersguus** [SanliFaez/OS4Physicists#7]
Wellicht goed om aandacht te besteden aan de WOO (wet open overheid, voorheen WOB) en de consequenties hiervan.

**Comment by hendelhendel** [comment]
Dag Guus,

Welke aspecten uit de WOO, is relevant voor de open science cursus? Gaat het om het open science inrichten van onderzoek dat de Nederlandse overheid laat doen?

Hendrik

**Comment by veldersguus** [comment]
Hoi,


Alles waar de overheid bij betrokken is moet openbaar worden gemaakt. Dat kan via WOO verzoeken, maar de overheid moet ook veel data en modellen actief openbaar maken.  Onderzoek dat de overheid uitzet kan hier waarschijnlijk ook onder kunnen vallen.  Hie hiermee ongegaan moet worden weet ik ook niet precies, maar het lijkt me goed als studenten zich hiervan bewust worden.


Groeten,

Guus



________________________________
